
# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# Opacity 
windowrule {
  name = windowrule-1
  opacity = 0.90 0.90
  workspace = 1
  idle_inhibit = fullscreen
  match:class = ^(Brave-browser)$
}

# windowrulev2 = opacity 0.80 0.80,class:^(Steam)$
# windowrulev2 = opacity 0.80 0.80,class:^(steam)$
windowrule {
  name = windowrule-2
  opacity = 0.80 0.80
  match:class = ^(steamwebhelper)$
}

windowrule {
  name = windowrule-3
  opacity = 0.80 0.80
  workspace = 5
  match:class = ^(Spotify)$
}

# windowrulev2 = opacity 0.80 0.80,class:^(Code)$
windowrule {
  name = windowrule-4
  opacity = 0.80 0.80
  match:class = ^(thunar)$
}

windowrule {
  name = windowrule-5
  opacity = 0.80 0.80
  match:class = ^(file-roller)$
}

windowrule {
  name = windowrule-6
  opacity = 0.80 0.80
  match:class = ^(nwg-look)$
}

windowrule {
  name = windowrule-7
  opacity = 0.80 0.80
  match:class = ^(qt5ct)$
}

windowrule {
  name = windowrule-8
  opacity = 0.80 0.80
  match:class = ^(discord)$ #Discord-Electron
}

windowrule {
  name = windowrule-9
  opacity = 0.80 0.80
  match:class = ^(WebCord)$ #WebCord-Electron
}

windowrule {
  name = windowrule-10
  opacity = 0.80 0.70
  float = on
  match:class = ^(pavucontrol)$
}

windowrule {
  name = windowrule-11
  opacity = 0.80 0.70
  float = on
  match:class = ^(org.kde.polkit-kde-authentication-agent-1)$
}

# windowrulev2 = opacity 0.80 0.80,class:^(org.telegram.desktop)$

# Position
# windowrulev2 = float,class:^(org.telegram.desktop)$
windowrule {
  name = windowrule-12
  float = on
  workspace = 1
  match:class = ^(TelegramDesktop)$ #
  match:initial_title = ^(?!Telegram$).*
}

windowrule {
  name = windowrule-13
  float = on
  match:title = ^(nmtui)$
}

windowrule {
  name = windowrule-14
  float = on
  match:title = ^(Media viewer)$
}

windowrule {
  name = windowrule-15
  float = on
  move = (75) ((monitor_h*0.44))
  size = 800 600
  match:title = ^(Volume Control)$
}

windowrule {
  name = windowrule-16
  float = on
  match:title = ^(Picture-in-Picture)$
}

windowrule {
  name = windowrule-17
  float = on
  match:class = ^(Viewnior)$
}

windowrule {
  name = windowrule-18
  float = on
  match:title = ^(DevTools)$
}

windowrule {
  name = windowrule-19
  float = on
  match:class = ^(file_progress)$
}

windowrule {
  name = windowrule-20
  float = on
  match:class = ^(confirm)$
}

windowrule {
  name = windowrule-21
  float = on
  match:class = ^(dialog)$
}

windowrule {
  name = windowrule-22
  float = on
  size = 800 600
  match:class = ^(download)$
}

windowrule {
  name = windowrule-23
  float = on
  match:class = ^(notification)$
}

windowrule {
  name = windowrule-24
  float = on
  match:class = ^(error)$
}

windowrule {
  name = windowrule-25
  float = on
  match:class = ^(confirmreset)$
}

windowrule {
  name = windowrule-26
  float = on
  size = 800 600
  match:title = ^(Open File)$
}

windowrule {
  name = windowrule-27
  float = on
  match:title = ^(branchdialog)$
}

windowrule {
  name = windowrule-28
  float = on
  match:title = ^(Confirm to replace files)
}

windowrule {
  name = windowrule-29
  float = on
  match:title = ^(File Operation Progress)
}



# Workspace 
windowrule {
  name = windowrule-30
  workspace = 2
  match:class = ^(discord)$
}

windowrule {
  name = windowrule-31
  workspace = 3
  match:class = ^(org.telegram.desktop)$
}

windowrule {
  name = windowrule-32
  workspace = 4
  match:class = ^(Code)$
}

windowrule {
  name = windowrule-33
  workspace = 4
  match:class = ^(code-url-handler)$
}


# Size
windowrule {
  name = windowrule-34
  size = 800 600
  match:title = ^(Save File)$
}


windowrule {
  name = windowrule-35
  idle_inhibit = focus
  match:class = ^(mpv)$
}


# xwaylandvideobridge
windowrule {
  name = windowrule-36
  opacity = 0.0 override 0.0 override
  no_anim = on
  no_focus = on
  no_initial_focus = on
  match:class = ^(xwaylandvideobridge)$
}

